import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    screens: {
      sm: '480px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1440px',
    },
    extend: {
      colors: {
        black: '#0A0A09',
        dark: '#111110',
        card: '#161614',
        surface: '#1C1C1A',
        white: '#FAFAF8',
        cream: '#F5F0E8',
        muted: {
          DEFAULT: '#8A8278',
          2: '#5A5550',
        },
        teal: {
          DEFAULT: '#00C9A7',
          bg: 'rgba(0,201,167,0.09)',
          border: 'rgba(0,201,167,0.25)',
          glow: 'rgba(0,201,167,0.055)',
        },
        border: {
          DEFAULT: 'rgba(255,255,255,0.07)',
          strong: 'rgba(255,255,255,0.13)',
        },
        whatsapp: '#25D366',
      },
      fontFamily: {
        cormorant: ['"Cormorant Garamond"', 'Georgia', 'serif'],
        syne: ['Syne', 'system-ui', 'sans-serif'],
        dm: ['"DM Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['clamp(40px,5.2vw,74px)', { lineHeight: '1.05', letterSpacing: '-0.015em', fontWeight: '300' }],
        'display-xl': ['clamp(36px,4vw,56px)', { lineHeight: '1.07', letterSpacing: '-0.012em', fontWeight: '300' }],
        'display-lg': ['clamp(30px,3.5vw,48px)', { lineHeight: '1.1', letterSpacing: '-0.01em', fontWeight: '300' }],
        'display-md': ['clamp(24px,2.5vw,36px)', { lineHeight: '1.15', letterSpacing: '-0.005em', fontWeight: '300' }],
        'display-sm': ['22px', { lineHeight: '1.2', fontWeight: '300' }],
        'ui-eyebrow': ['11px', { lineHeight: '1', letterSpacing: '0.18em' }],
        'ui-nav': ['12px', { lineHeight: '1.4', letterSpacing: '0.02em' }],
        'ui-label': ['11px', { lineHeight: '1.4', letterSpacing: '0.08em' }],
        'ui-btn': ['13px', { lineHeight: '1', letterSpacing: '0.01em' }],
        'ui-badge': ['10px', { lineHeight: '1', letterSpacing: '0.1em' }],
        'body-lg': ['15px', { lineHeight: '1.75' }],
        'body-base': ['14px', { lineHeight: '1.78' }],
        'body-sm': ['13.5px', { lineHeight: '1.72' }],
        'body-xs': ['13px', { lineHeight: '1.65' }],
        'body-caption': ['12px', { lineHeight: '1.6' }],
        'num-lg': ['62px', { lineHeight: '0.9', fontWeight: '300' }],
        'num-md': ['52px', { lineHeight: '1', fontWeight: '300' }],
        quote: ['72px', { lineHeight: '0.6', fontWeight: '300' }],
        decor: ['100px', { lineHeight: '1', fontWeight: '300' }],
        'title-sm': ['26px', { lineHeight: '1.2', fontWeight: '300' }],
        'icon-lg': ['20px', { lineHeight: '1', fontWeight: '300' }],
      },
      spacing: {
        sec: 'clamp(74px, 9vw, 112px)',
        'sec-sm': 'clamp(58px, 8vw, 84px)',
        gutter: '48px',
        'gut-md': '28px',
        'gut-sm': '20px',
        'col-gap': '24px',
        'col-md': '18px',
        'col-sm': '12px',
        'card-gap': '2px',
        'tile-gap': '1px',
        'card-pad': 'clamp(28px, 4vw, 38px)',
        'svc-pad': 'clamp(28px, 5vw, 46px)',
        'faq-pad': 'clamp(20px, 3.4vw, 28px)',
        nav: 'clamp(62px, 8vh, 70px)',
        'hero-pb': 'clamp(60px, 10vh, 88px)',
        'hero-pb-sm': 'clamp(42px, 8vh, 58px)',
        'header-gap': 'clamp(34px, 4.6vw, 56px)',
        about: 'clamp(80px, 11vw, 132px)',
        'mq-pad': '190px',
        wa: '50px',
        'page-top': 'clamp(98px, 10vw, 132px)',
        'page-top-sm': 'clamp(86px, 13vw, 108px)',
        'hero-min': '640px',
      },
      borderRadius: {
        btn: '8px',
        badge: '4px',
        pill: '100px',
        input: '7px',
        card: '0px',
      },
      maxWidth: {
        site: '1180px',
        copy: '600px',
        'hero-body': '680px',
        'cta-body': '480px',
        'copy-sm': '560px',
        'work-desc': '520px',
        'process-desc': '580px',
        'footer-brand': '240px',
        'hero-title': '760px',
        'content-lg': '760px',
      },
      zIndex: {
        base: '0',
        above: '10',
        hero: '3',
        heroOv: '1',
        sticky: '50',
        nav: '500',
        mob: '499',
        waFloat: '400',
        progressBar: '600',
        cursor: '9999',
        ring: '9998',
      },
      animation: {
        marquee: 'marquee 28s linear infinite',
        'scroll-pulse': 'scroll-pulse 2.2s ease-in-out infinite',
      },
      keyframes: {
        marquee: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-50%)' },
        },
        'scroll-pulse': {
          '0%,100%': { opacity: '0.38' },
          '50%': { opacity: '0.12' },
        },
      },
      backgroundImage: {
        'grid-pattern': 'linear-gradient(rgba(255,255,255,0.06) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,0.06) 1px,transparent 1px)',
      },
      backgroundSize: {
        'grid-52': '52px 52px',
      },
      transitionTimingFunction: {
        'mobile-nav': 'cubic-bezier(0.77, 0, 0.175, 1)',
      },
    },
  },
  plugins: [],
} satisfies Config
