// Responsive 400/800/1200 variants generated by scripts/generate-responsive-images.mjs
// (never upscaled beyond source). Replaces full-resolution fallbacks that were
// bundled but never actually reachable from the render below.
import drakeHome400 from "../assets/work/drake-seaside/hero-bg-400.webp";
import drakeHome800 from "../assets/work/drake-seaside/hero-bg-800.webp";
import drakeHome1200 from "../assets/work/drake-seaside/hero-bg-1200.webp";
import drakeHomeAvif400 from "../assets/work/drake-seaside/hero-bg-400.avif";
import drakeHomeAvif800 from "../assets/work/drake-seaside/hero-bg-800.avif";
import drakeHomeAvif1200 from "../assets/work/drake-seaside/hero-bg-1200.avif";
import ogImage from "../assets/logo/og-image.png";
import formaHome400 from "../assets/work/forma studio/forma-400.webp";
import formaHome800 from "../assets/work/forma studio/forma-800.webp";
import formaHome1200 from "../assets/work/forma studio/forma-1200.webp";
import formaHomeAvif400 from "../assets/work/forma studio/forma-400.avif";
import formaHomeAvif800 from "../assets/work/forma studio/forma-800.avif";
import formaHomeAvif1200 from "../assets/work/forma studio/forma-1200.avif";
import takamakaHome400 from "../assets/work/takamaka-house/takamaka-400.webp";
import takamakaHome800 from "../assets/work/takamaka-house/takamaka-800.webp";
import takamakaHome1200 from "../assets/work/takamaka-house/takamaka-1200.webp";
import takamakaHomeAvif400 from "../assets/work/takamaka-house/takamaka-400.avif";
import takamakaHomeAvif800 from "../assets/work/takamaka-house/takamaka-800.avif";
import takamakaHomeAvif1200 from "../assets/work/takamaka-house/takamaka-1200.avif";
import beautyPreviewWebp800 from "../assets/work/demo-beauty/demo-beauty 600.webp";
import businessFacts from "./businessFacts.json";

export { businessFacts };

export const siteConfig = {
  ...businessFacts.site,
  ogImage,
};

export const emailTemplate = {
  subject: "New Project Inquiry - [Business Name]",
  body: `Hi Horizon Digital,

I'd like to discuss a new website project.

Business name:
Industry:
Current website (if any):

Main goal for the website:
(e.g. more bookings, more inquiries, clearer brand presence)

Estimated timeline:
(e.g. ASAP, 1-2 months, flexible)

Anything else you'd like us to know:

Looking forward to your reply.`,
};

export const navLinks = [
  { label: "Services", path: businessFacts.site.servicesPath },
  { label: "Work", path: "/work" },
  { label: "Pricing", path: businessFacts.site.pricingPath },
  { label: "Insights", path: "/insights" },
  { label: "About", path: "/about" },
];

export type ServicePathway = "Build or improve your website" | "Improve visibility and measurement";

export type ServiceCatalogueEntry = {
  id: string;
  pathway: ServicePathway;
  serviceType: "website-project" | "website-feature" | "managed-service" | "support" | "consultation-review" | "implementation";
  title: string;
  description: string;
  price: string;
  websiteRedesignRequired: boolean;
  accessRequirement?: string;
  pricingPath?: string;
};

export const trustItems = businessFacts.trustItems;
export const services = businessFacts.business.services;
export const serviceCatalogue = businessFacts.serviceCatalogue as ServiceCatalogueEntry[];
export const servicesByPathway = (pathway: ServicePathway) =>
  serviceCatalogue.filter((service) => service.pathway === pathway);
export const existingWebsiteFlow = businessFacts.existingWebsiteFlow;
export const serviceScopeBoundaries = businessFacts.serviceScopeBoundaries;
export const servicePages = businessFacts.servicePages;
export const serviceNavigation = servicePages.navigation;
export type ServicePageKey = Exclude<keyof typeof servicePages, "navigation">;
export const getServicePage = <Key extends ServicePageKey>(key: Key): (typeof servicePages)[Key] => servicePages[key];
export const getServiceBoundaries = (ids: readonly string[]) =>
  ids.map((id) => serviceScopeBoundaries.find((boundary) => boundary.id === id)).filter(Boolean);
export const addOns = businessFacts.addOns.map((item) => item.title);
export const projectSteps = businessFacts.projectSteps;
export const servicesPricingIntro = businessFacts.servicesPricingIntro;

export const foundationPackage = businessFacts.packages.find((item) => item.id === "foundation")!;
export const starterPackage = businessFacts.packages.find((item) => item.id === "starter")!;
export const growthPackage = businessFacts.packages.find((item) => item.id === "growth")!;
export const customPackage = businessFacts.packages.find((item) => item.id === "custom")!;

export const addOnItems = businessFacts.addOns;
export const paymentTerms = businessFacts.paymentTerms;
export const hostingPlan = businessFacts.hosting;
export const stabilisationPlan = businessFacts.stabilisation;
export const faqs = businessFacts.faqs;
export const homeFaqCategories = businessFacts.homeFaqCategories;

export const trustStatement = [
  "Clear scope",
  "Published starting prices",
  "Defined revisions",
  "Direct communication",
  "Written project terms",
];

const portfolioAssets: Record<
  string,
  {
    image: string;
    imageSrcSet?: string;
    imageAvifSrcSet?: string;
    imageSizes?: string;
    imagePosition?: string;
  }
> = {
  "drake-seaside": {
    image: drakeHome800,
    imageSrcSet: `${drakeHome400} 400w, ${drakeHome800} 800w, ${drakeHome1200} 1200w`,
    imageAvifSrcSet: `${drakeHomeAvif400} 400w, ${drakeHomeAvif800} 800w, ${drakeHomeAvif1200} 1200w`,
    imageSizes: "(min-width: 1024px) 58vw, 100vw",
  },
  "forma-studio": {
    image: formaHome800,
    imageSrcSet: `${formaHome400} 400w, ${formaHome800} 800w, ${formaHome1200} 1200w`,
    imageAvifSrcSet: `${formaHomeAvif400} 400w, ${formaHomeAvif800} 800w, ${formaHomeAvif1200} 1200w`,
    imageSizes: "(min-width: 640px) 9rem, 100vw",
    imagePosition: "center 40%",
  },
  "takamaka-house": {
    image: takamakaHome800,
    imageSrcSet: `${takamakaHome400} 400w, ${takamakaHome800} 800w, ${takamakaHome1200} 1200w`,
    imageAvifSrcSet: `${takamakaHomeAvif400} 400w, ${takamakaHomeAvif800} 800w, ${takamakaHomeAvif1200} 1200w`,
    imageSizes: "(min-width: 640px) 9rem, 100vw",
    imagePosition: "center 55%",
  },
  "beauty-demo": {
    image: beautyPreviewWebp800,
  },
};

export const workItems = businessFacts.portfolio.map((item) => ({
  ...item,
  ...portfolioAssets[item.id],
}));

export const liveClientProject = workItems.find((item) => item.id === "drake-seaside")!;

const supportDaysFromPackage = (pkg: { includes: { title: string }[] }) => {
  const entry = pkg.includes.find((item) => /post-launch support/i.test(item.title));
  const days = entry ? Number(entry.title.match(/\d+/)?.[0]) : undefined;
  return days;
};

export const supportDaysRange = {
  min: supportDaysFromPackage(foundationPackage),
  max: supportDaysFromPackage(growthPackage),
};

export const homeProofPoints = [
  {
    label: "Live client work",
    value: liveClientProject.title,
    href: liveClientProject.url,
  },
  {
    label: "Published pricing",
    value: foundationPackage.price,
  },
  {
    label: "Our process",
    value: `${projectSteps.length}-stage process`,
  },
  {
    label: "Post-launch support",
    value: `${supportDaysRange.min}–${supportDaysRange.max} days`,
  },
];
